obstacles:
- angular_speed: 0.8
  is_dynamic: true
  name: Obstacle1
  position:
  - 1.46
  - -0.22
  - -0.95
  radius: 0.15
  velocity:
  - 0.88
  - 1.48
  - 0.95
- angular_speed: 0.94
  is_dynamic: true
  name: Obstacle2
  position:
  - 2.35
  - 1.72
  - 0.63
  radius: 0.15
  velocity:
  - 1.47
  - 1.34
  - 1.43
- angular_speed: 0.93
  is_dynamic: true
  name: Obstacle3
  position:
  - 8.63
  - 6.82
  - -0.44
  radius: 0.15
  velocity:
  - 1.17
  - 0.87
  - 1.31
- angular_speed: 0.32
  is_dynamic: true
  name: Obstacle4
  position:
  - 7.97
  - 7.06
  - 0.49
  radius: 0.15
  velocity:
  - 0.85
  - 1.42
  - 1.21
- angular_speed: 0.44
  is_dynamic: true
  name: Obstacle5
  position:
  - 3.24
  - 4.48
  - 0.7
  radius: 0.15
  velocity:
  - 0.95
  - 0.99
  - 1.49
- angular_speed: 0.23
  is_dynamic: true
  name: Obstacle6
  position:
  - 3.42
  - 4.93
  - 0.13
  radius: 0.15
  velocity:
  - 1.4
  - 1.07
  - 1.34
- angular_speed: 0.41
  is_dynamic: true
  name: Obstacle7
  position:
  - 3.37
  - 2.31
  - 0.41
  radius: 0.15
  velocity:
  - 0.86
  - 1.19
  - 0.89
- angular_speed: 0.43
  is_dynamic: true
  name: Obstacle8
  position:
  - 5.38
  - 3.72
  - -0.57
  radius: 0.15
  velocity:
  - 1.4
  - 1.35
  - 1.12
- angular_speed: 0.47
  is_dynamic: true
  name: Obstacle9
  position:
  - 2.88
  - 4.17
  - 0.3
  radius: 0.15
  velocity:
  - 1.18
  - 1.09
  - 1.47
- angular_speed: 0.34
  is_dynamic: true
  name: Obstacle10
  position:
  - 5.29
  - 4.52
  - -0.56
  radius: 0.15
  velocity:
  - 1.33
  - 1.47
  - 1.11
- angular_speed: 0.76
  is_dynamic: true
  name: Obstacle11
  position:
  - 6.3
  - 8.21
  - -0.91
  radius: 0.15
  velocity:
  - 0.91
  - 1.47
  - 1.26
- angular_speed: 0.58
  is_dynamic: true
  name: Obstacle12
  position:
  - 5.22
  - 6.72
  - 0.17
  radius: 0.15
  velocity:
  - 1.35
  - 1.14
  - 1.14
- angular_speed: 0.81
  is_dynamic: true
  name: Obstacle13
  position:
  - 5.73
  - 5.72
  - -0.75
  radius: 0.15
  velocity:
  - 1.17
  - 1.42
  - 1.24
- angular_speed: 0.24
  is_dynamic: true
  name: Obstacle14
  position:
  - 3.95
  - 5.28
  - 0.22
  radius: 0.15
  velocity:
  - 1.35
  - 1.3
  - 1.07
- angular_speed: 0.77
  is_dynamic: true
  name: Obstacle15
  position:
  - 2.82
  - 2.07
  - 0.27
  radius: 0.15
  velocity:
  - 1.41
  - 1.2
  - 1.44
- angular_speed: 0.71
  is_dynamic: true
  name: Obstacle16
  position:
  - 8.35
  - 9.74
  - -0.32
  radius: 0.15
  velocity:
  - 1.11
  - 0.92
  - 1.11
- angular_speed: 0.93
  is_dynamic: true
  name: Obstacle17
  position:
  - 2.59
  - 0.7
  - -0.14
  radius: 0.15
  velocity:
  - 0.88
  - 0.95
  - 1.49
- angular_speed: 0.97
  is_dynamic: true
  name: Obstacle18
  position:
  - 7.81
  - 6.7
  - -0.8
  radius: 0.15
  velocity:
  - 1.21
  - 1.26
  - 1.27
- angular_speed: 0.36
  is_dynamic: true
  name: Obstacle19
  position:
  - 1.46
  - 1.9
  - 0.3
  radius: 0.15
  velocity:
  - 1.03
  - 1.09
  - 1.32
- angular_speed: 0.46
  is_dynamic: true
  name: Obstacle20
  position:
  - 5.11
  - 4.07
  - 0.12
  radius: 0.15
  velocity:
  - 0.94
  - 1.13
  - 1.04
- angular_speed: 0.31
  is_dynamic: true
  name: Obstacle21
  position:
  - 2.59
  - 2.12
  - -0.06
  radius: 0.15
  velocity:
  - 0.95
  - 1.25
  - 1.19
- angular_speed: 0.56
  is_dynamic: true
  name: Obstacle22
  position:
  - 6.7
  - 6.33
  - -0.06
  radius: 0.15
  velocity:
  - 1.49
  - 1.16
  - 1.41
- angular_speed: 0.56
  is_dynamic: true
  name: Obstacle23
  position:
  - 4.25
  - 2.61
  - -0.64
  radius: 0.15
  velocity:
  - 0.96
  - 0.9
  - 1.21
- angular_speed: 0.53
  is_dynamic: true
  name: Obstacle24
  position:
  - 4.71
  - 5.45
  - -0.85
  radius: 0.15
  velocity:
  - 1.06
  - 1.21
  - 0.85
- angular_speed: 0.49
  is_dynamic: true
  name: Obstacle25
  position:
  - 1.41
  - -0.27
  - 0.94
  radius: 0.15
  velocity:
  - 1.43
  - 1.29
  - 1.06
- angular_speed: 0.46
  is_dynamic: true
  name: Obstacle26
  position:
  - 8.69
  - 6.91
  - -0.55
  radius: 0.15
  velocity:
  - 1.34
  - 0.93
  - 1.0
- angular_speed: 0.57
  is_dynamic: true
  name: Obstacle27
  position:
  - 8.98
  - 8.64
  - -0.33
  radius: 0.15
  velocity:
  - 1.37
  - 0.83
  - 0.81
- angular_speed: 0.36
  is_dynamic: true
  name: Obstacle28
  position:
  - 1.27
  - -0.68
  - 0.96
  radius: 0.15
  velocity:
  - 1.3
  - 1.37
  - 0.97
- angular_speed: 0.38
  is_dynamic: true
  name: Obstacle29
  position:
  - 1.02
  - 0.1
  - -0.11
  radius: 0.15
  velocity:
  - 1.2
  - 0.82
  - 0.99
- angular_speed: 0.68
  is_dynamic: true
  name: Obstacle30
  position:
  - 3.96
  - 2.94
  - -0.08
  radius: 0.15
  velocity:
  - 0.93
  - 1.13
  - 1.31
- angular_speed: 0.33
  is_dynamic: true
  name: Obstacle31
  position:
  - 2.06
  - 3.5
  - -0.96
  radius: 0.15
  velocity:
  - 1.05
  - 1.49
  - 1.5
- angular_speed: 0.93
  is_dynamic: true
  name: Obstacle32
  position:
  - 1.64
  - 2.44
  - 0.36
  radius: 0.15
  velocity:
  - 1.21
  - 0.89
  - 1.29
- angular_speed: 0.31
  is_dynamic: true
  name: Obstacle33
  position:
  - 2.63
  - 1.22
  - 0.14
  radius: 0.15
  velocity:
  - 1.32
  - 1.29
  - 1.04
- angular_speed: 0.71
  is_dynamic: true
  name: Obstacle34
  position:
  - 5.81
  - 7.37
  - -0.48
  radius: 0.15
  velocity:
  - 1.4
  - 1.04
  - 0.87
- angular_speed: 0.52
  is_dynamic: true
  name: Obstacle35
  position:
  - 5.33
  - 5.38
  - 0.48
  radius: 0.15
  velocity:
  - 1.04
  - 1.42
  - 0.96
- angular_speed: 0.71
  is_dynamic: true
  name: Obstacle36
  position:
  - 6.24
  - 4.43
  - -0.64
  radius: 0.15
  velocity:
  - 0.98
  - 1.18
  - 1.06
- angular_speed: 0.87
  is_dynamic: true
  name: Obstacle37
  position:
  - 8.16
  - 10.01
  - 0.62
  radius: 0.15
  velocity:
  - 1.38
  - 1.01
  - 0.94
- angular_speed: 0.75
  is_dynamic: true
  name: Obstacle38
  position:
  - 7.18
  - 5.75
  - 0.31
  radius: 0.15
  velocity:
  - 1.19
  - 1.49
  - 0.85
- angular_speed: 0.92
  is_dynamic: true
  name: Obstacle39
  position:
  - 8.88
  - 10.46
  - 0.94
  radius: 0.15
  velocity:
  - 1.15
  - 1.42
  - 1.45
- angular_speed: 0.96
  is_dynamic: true
  name: Obstacle40
  position:
  - 4.61
  - 6.6
  - 0.22
  radius: 0.15
  velocity:
  - 0.98
  - 1.35
  - 0.82
- angular_speed: 0.78
  is_dynamic: true
  name: Obstacle41
  position:
  - 6.74
  - 6.88
  - -0.15
  radius: 0.15
  velocity:
  - 0.8
  - 1.18
  - 1.45
- angular_speed: 0.92
  is_dynamic: true
  name: Obstacle42
  position:
  - 6.92
  - 8.25
  - 0.33
  radius: 0.15
  velocity:
  - 1.43
  - 0.99
  - 1.0
- angular_speed: 0.78
  is_dynamic: true
  name: Obstacle43
  position:
  - 6.78
  - 8.49
  - -0.42
  radius: 0.15
  velocity:
  - 1.31
  - 1.25
  - 1.32
- angular_speed: 0.74
  is_dynamic: true
  name: Obstacle44
  position:
  - 7.95
  - 7.54
  - 0.52
  radius: 0.15
  velocity:
  - 1.3
  - 1.05
  - 0.86
- angular_speed: 0.28
  is_dynamic: true
  name: Obstacle45
  position:
  - 2.95
  - 2.4
  - -0.76
  radius: 0.15
  velocity:
  - 1.1
  - 1.24
  - 1.44
- angular_speed: 0.99
  is_dynamic: true
  name: Obstacle46
  position:
  - 8.06
  - 7.14
  - -0.62
  radius: 0.15
  velocity:
  - 1.46
  - 1.43
  - 0.92
- angular_speed: 0.92
  is_dynamic: true
  name: Obstacle47
  position:
  - 4.94
  - 4.64
  - -0.6
  radius: 0.15
  velocity:
  - 1.06
  - 1.25
  - 1.06
- angular_speed: 0.35
  is_dynamic: true
  name: Obstacle48
  position:
  - 2.29
  - 1.65
  - 0.67
  radius: 0.15
  velocity:
  - 1.47
  - 1.11
  - 1.09
- angular_speed: 0.69
  is_dynamic: true
  name: Obstacle49
  position:
  - 8.63
  - 8.5
  - -0.77
  radius: 0.15
  velocity:
  - 1.08
  - 1.0
  - 0.81
- angular_speed: 0.21
  is_dynamic: true
  name: Obstacle50
  position:
  - 4.88
  - 3.48
  - -0.79
  radius: 0.15
  velocity:
  - 1.29
  - 1.36
  - 0.99
