obstacles:
- angular_speed: 0.6
  is_dynamic: true
  name: Obstacle1
  position:
  - 6.9
  - 0.37
  - -0.39
  radius: 0.15
  velocity:
  - 1.13
  - 1.41
  - 1.07
- angular_speed: 0.52
  is_dynamic: true
  name: Obstacle2
  position:
  - 6.15
  - 0.24
  - -0.97
  radius: 0.15
  velocity:
  - 1.27
  - 1.38
  - 1.15
- angular_speed: 0.23
  is_dynamic: true
  name: Obstacle3
  position:
  - 6.67
  - 0.9
  - -0.33
  radius: 0.15
  velocity:
  - 1.11
  - 1.39
  - 0.87
- angular_speed: 0.38
  is_dynamic: true
  name: Obstacle4
  position:
  - 8.29
  - -1.35
  - -0.85
  radius: 0.15
  velocity:
  - 1.5
  - 1.13
  - 0.86
- angular_speed: 0.32
  is_dynamic: true
  name: Obstacle5
  position:
  - 6.72
  - -1.94
  - 0.78
  radius: 0.15
  velocity:
  - 1.36
  - 1.34
  - 0.98
- angular_speed: 0.49
  is_dynamic: true
  name: Obstacle6
  position:
  - 2.08
  - -1.1
  - 0.63
  radius: 0.15
  velocity:
  - 1.25
  - 1.01
  - 0.93
- angular_speed: 0.67
  is_dynamic: true
  name: Obstacle7
  position:
  - 7.22
  - 0.02
  - -0.87
  radius: 0.15
  velocity:
  - 1.27
  - 0.95
  - 0.9
- angular_speed: 0.8
  is_dynamic: true
  name: Obstacle8
  position:
  - 2.03
  - 1.71
  - -0.77
  radius: 0.15
  velocity:
  - 1.03
  - 1.41
  - 1.15
- angular_speed: 0.64
  is_dynamic: true
  name: Obstacle9
  position:
  - 4.72
  - 1.84
  - 0.83
  radius: 0.15
  velocity:
  - 1.15
  - 1.12
  - 1.46
- angular_speed: 0.44
  is_dynamic: true
  name: Obstacle10
  position:
  - 7.31
  - 0.14
  - 0.5
  radius: 0.15
  velocity:
  - 1.36
  - 1.22
  - 1.07
- angular_speed: 0.44
  is_dynamic: true
  name: Obstacle11
  position:
  - 8.7
  - 0.43
  - 0.65
  radius: 0.15
  velocity:
  - 0.98
  - 1.16
  - 0.92
- angular_speed: 0.31
  is_dynamic: true
  name: Obstacle12
  position:
  - 7.24
  - 1.82
  - -0.13
  radius: 0.15
  velocity:
  - 0.98
  - 1.48
  - 1.35
- angular_speed: 0.28
  is_dynamic: true
  name: Obstacle13
  position:
  - 5.99
  - -0.17
  - 0.94
  radius: 0.15
  velocity:
  - 1.15
  - 1.09
  - 1.35
- angular_speed: 0.72
  is_dynamic: true
  name: Obstacle14
  position:
  - 6.22
  - -1.4
  - -0.1
  radius: 0.15
  velocity:
  - 0.97
  - 0.96
  - 1.4
- angular_speed: 0.58
  is_dynamic: true
  name: Obstacle15
  position:
  - 6.47
  - -0.85
  - 0.23
  radius: 0.15
  velocity:
  - 1.42
  - 1.12
  - 0.92
- angular_speed: 0.29
  is_dynamic: true
  name: Obstacle16
  position:
  - 4.64
  - -0.35
  - -0.68
  radius: 0.15
  velocity:
  - 0.83
  - 1.39
  - 1.14
- angular_speed: 0.96
  is_dynamic: true
  name: Obstacle17
  position:
  - 6.02
  - 1.34
  - 0.01
  radius: 0.15
  velocity:
  - 1.1
  - 0.84
  - 0.85
- angular_speed: 0.43
  is_dynamic: true
  name: Obstacle18
  position:
  - 1.95
  - 0.59
  - -0.59
  radius: 0.15
  velocity:
  - 1.33
  - 0.91
  - 1.1
- angular_speed: 0.9
  is_dynamic: true
  name: Obstacle19
  position:
  - 4.58
  - -0.35
  - 0.2
  radius: 0.15
  velocity:
  - 1.42
  - 1.31
  - 1.09
- angular_speed: 0.34
  is_dynamic: true
  name: Obstacle20
  position:
  - 2.42
  - -1.59
  - 0.56
  radius: 0.15
  velocity:
  - 1.11
  - 1.09
  - 1.41
- angular_speed: 0.47
  is_dynamic: true
  name: Obstacle21
  position:
  - 1.87
  - -1.53
  - 0.87
  radius: 0.15
  velocity:
  - 1.46
  - 0.97
  - 1.13
- angular_speed: 0.93
  is_dynamic: true
  name: Obstacle22
  position:
  - 3.54
  - 0.68
  - -0.51
  radius: 0.15
  velocity:
  - 1.43
  - 0.83
  - 1.28
- angular_speed: 0.58
  is_dynamic: true
  name: Obstacle23
  position:
  - 8.97
  - 1.4
  - -1.0
  radius: 0.15
  velocity:
  - 1.42
  - 0.85
  - 1.01
- angular_speed: 0.2
  is_dynamic: true
  name: Obstacle24
  position:
  - 6.12
  - -1.64
  - -0.84
  radius: 0.15
  velocity:
  - 1.33
  - 1.34
  - 1.46
- angular_speed: 0.6
  is_dynamic: true
  name: Obstacle25
  position:
  - 3.13
  - -1.64
  - -0.36
  radius: 0.15
  velocity:
  - 0.9
  - 1.45
  - 0.86
- angular_speed: 0.85
  is_dynamic: true
  name: Obstacle26
  position:
  - 1.41
  - -0.79
  - -0.11
  radius: 0.15
  velocity:
  - 1.48
  - 0.86
  - 0.94
- angular_speed: 0.57
  is_dynamic: true
  name: Obstacle27
  position:
  - 6.87
  - -1.67
  - -0.23
  radius: 0.15
  velocity:
  - 1.28
  - 1.36
  - 1.4
- angular_speed: 0.83
  is_dynamic: true
  name: Obstacle28
  position:
  - 6.41
  - 1.78
  - 0.78
  radius: 0.15
  velocity:
  - 0.83
  - 1.07
  - 1.49
- angular_speed: 0.54
  is_dynamic: true
  name: Obstacle29
  position:
  - 8.28
  - 0.43
  - -0.47
  radius: 0.15
  velocity:
  - 0.85
  - 1.34
  - 1.04
- angular_speed: 0.38
  is_dynamic: true
  name: Obstacle30
  position:
  - 4.45
  - 1.18
  - -0.2
  radius: 0.15
  velocity:
  - 1.15
  - 0.97
  - 0.97
- angular_speed: 0.4
  is_dynamic: true
  name: Obstacle31
  position:
  - 4.33
  - -1.1
  - 0.03
  radius: 0.15
  velocity:
  - 1.38
  - 1.23
  - 1.21
- angular_speed: 0.68
  is_dynamic: true
  name: Obstacle32
  position:
  - 4.39
  - 0.95
  - 0.91
  radius: 0.15
  velocity:
  - 1.37
  - 1.24
  - 1.3
- angular_speed: 0.94
  is_dynamic: true
  name: Obstacle33
  position:
  - 6.14
  - -1.15
  - 0.85
  radius: 0.15
  velocity:
  - 1.21
  - 1.34
  - 0.94
- angular_speed: 0.83
  is_dynamic: true
  name: Obstacle34
  position:
  - 2.48
  - 0.28
  - 0.12
  radius: 0.15
  velocity:
  - 1.01
  - 1.13
  - 1.28
- angular_speed: 1.0
  is_dynamic: true
  name: Obstacle35
  position:
  - 1.75
  - -0.81
  - 0.23
  radius: 0.15
  velocity:
  - 1.16
  - 1.36
  - 1.35
- angular_speed: 0.73
  is_dynamic: true
  name: Obstacle36
  position:
  - 2.63
  - -0.53
  - 0.36
  radius: 0.15
  velocity:
  - 1.49
  - 1.35
  - 0.91
- angular_speed: 0.3
  is_dynamic: true
  name: Obstacle37
  position:
  - 7.11
  - 0.79
  - -0.7
  radius: 0.15
  velocity:
  - 1.4
  - 1.44
  - 0.99
- angular_speed: 0.27
  is_dynamic: true
  name: Obstacle38
  position:
  - 7.4
  - -0.3
  - -0.95
  radius: 0.15
  velocity:
  - 1.23
  - 1.45
  - 1.14
- angular_speed: 0.27
  is_dynamic: true
  name: Obstacle39
  position:
  - 7.16
  - -0.56
  - 0.77
  radius: 0.15
  velocity:
  - 1.4
  - 1.5
  - 1.14
- angular_speed: 0.6
  is_dynamic: true
  name: Obstacle40
  position:
  - 6.8
  - -1.75
  - -0.6
  radius: 0.15
  velocity:
  - 1.04
  - 1.37
  - 1.33
- angular_speed: 0.95
  is_dynamic: true
  name: Obstacle41
  position:
  - 8.41
  - -0.77
  - 0.74
  radius: 0.15
  velocity:
  - 1.22
  - 1.23
  - 1.27
- angular_speed: 0.54
  is_dynamic: true
  name: Obstacle42
  position:
  - 6.38
  - 0.68
  - 0.61
  radius: 0.15
  velocity:
  - 0.86
  - 1.43
  - 1.16
- angular_speed: 0.86
  is_dynamic: true
  name: Obstacle43
  position:
  - 7.62
  - -0.12
  - -0.31
  radius: 0.15
  velocity:
  - 1.42
  - 0.91
  - 1.32
- angular_speed: 0.41
  is_dynamic: true
  name: Obstacle44
  position:
  - 4.71
  - -1.36
  - 0.77
  radius: 0.15
  velocity:
  - 1.49
  - 1.14
  - 1.28
- angular_speed: 0.38
  is_dynamic: true
  name: Obstacle45
  position:
  - 6.16
  - -1.26
  - 0.01
  radius: 0.15
  velocity:
  - 1.4
  - 1.32
  - 1.0
- angular_speed: 0.55
  is_dynamic: true
  name: Obstacle46
  position:
  - 4.89
  - -0.77
  - -0.76
  radius: 0.15
  velocity:
  - 1.39
  - 1.45
  - 1.29
- angular_speed: 0.74
  is_dynamic: true
  name: Obstacle47
  position:
  - 7.93
  - 0.08
  - -0.84
  radius: 0.15
  velocity:
  - 1.07
  - 1.13
  - 1.28
- angular_speed: 0.88
  is_dynamic: true
  name: Obstacle48
  position:
  - 2.07
  - 1.88
  - 0.69
  radius: 0.15
  velocity:
  - 1.49
  - 1.18
  - 0.93
- angular_speed: 0.47
  is_dynamic: true
  name: Obstacle49
  position:
  - 7.37
  - -1.24
  - -0.78
  radius: 0.15
  velocity:
  - 1.45
  - 1.11
  - 0.82
- angular_speed: 0.92
  is_dynamic: true
  name: Obstacle50
  position:
  - 2.45
  - -0.43
  - 0.52
  radius: 0.15
  velocity:
  - 1.38
  - 1.3
  - 0.93